description: Add, remove, and edit entries in /etc/hosts; preserves arbitrary comments
tags:
  - hosts
  - config
  - network

links:
  - https://gitlab.com/dbohdan/hosts

alternatives:
  - hostctl
  - hostess
